repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run black
        language: system
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: pdm run flake8
        language: system
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pdm run isort
        language: system
        types:
          - file
          - python